title: /bin/hacken
email: your-email@example.com
description: >-
  Make- & Hackspace Bingen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://binhacken.de"

# Build settings
theme: minima
plugins:
  - jekyll-feed
